variables:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

build_linux:
  image: rust:latest
  tags:
    - linux
    - shared
  before_script:
    - apt update && apt install -y libseccomp-dev libseccomp2
  script:
    - cargo build --workspace --all-targets --all-features --verbose
    - mkdir -p artifacts-tests/workers/
    - cargo build --tests --message-format=json | tests/copy_artifacts.py artifacts-tests/
  artifacts:
    expire_in: 1h
    name: tests-linux
    paths:
      - artifacts-tests/

build_windows:
  tags:
    - shared-windows
  variables:
    RUSTUP_HOME: .rustup
    CARGO_HOME: .cargo
  before_script:
    - Invoke-WebRequest -Uri https://win.rustup.rs/x86_64 -OutFile rustup-init.exe
    - .\rustup-init.exe -y --default-toolchain stable-x86_64-pc-windows-msvc
    - choco install python --yes --force --no-progress
    - $env:Path=[System.Environment]::GetEnvironmentVariable("Path","Machine")+";"+[System.Environment]::GetEnvironmentVariable("Path","User")
  script:
    - cargo build --workspace --all-targets --all-features --verbose
    - mkdir -p artifacts-tests/workers/
    - cargo build --tests --message-format=json | python tests/copy_artifacts.py artifacts-tests/
  artifacts:
    expire_in: 1h
    name: tests-windows
    paths:
      - artifacts-tests/

#test_linux:
#  image: debian:latest
#  tags:
#    - linux
#  needs:
#    - job: build_linux
#      artifacts: true
#  before_script:
#    - apt update && apt install -y libseccomp2
#  script:
#    - tests/run.sh artifacts-tests/
