variables:
  CARGO_TERM_COLOR: always

#build_linux:
#  image: rust:latest
#  tags:
#    - linux
#    - shared
#  before_script:
#    - apt update && apt install -y libseccomp-dev libseccomp2
#  script:
#    - cargo build --workspace --all-targets --all-features --verbose
#    - mkdir -p artifacts-tests/workers/
#    - cargo build --tests --message-format=json | tests/copy_artifacts.py artifacts-tests/
#  artifacts:
#    expire_in: 1h
#    name: tests-linux
#    paths:
#      - artifacts-tests/

build_windows:
  tags:
    - windows
    - selfhosted
    - builder
  variables:
    RUSTUP_HOME: .rustup
    CARGO_HOME: .cargo
    RUSTFLAGS: -D warnings -Ctarget-feature=+crt-static
  before_script:
    - Invoke-WebRequest -Uri https://win.rustup.rs/x86_64 -OutFile rustup-init.exe
    - .\rustup-init.exe -y --default-toolchain stable-x86_64-pc-windows-msvc
    - $env:Path=[System.Environment]::GetEnvironmentVariable("Path","Machine")+";"+[System.Environment]::GetEnvironmentVariable("Path","User")
  script:
    - cargo build --workspace --all-targets --all-features --verbose
    - mkdir -p artifacts-tests/workers/
    - cargo build --tests --message-format=json | python tests/copy_artifacts.py artifacts-tests/
  artifacts:
    expire_in: 1h
    name: tests-windows
    paths:
      - artifacts-tests/

test_win10_latest_x64:
  tags:
    - windows
    - selfhosted
    - win10
    - amd64
    - latest
  needs:
    - job: build_windows
      artifacts: true
  script:
    - tests/run.ps1 artifacts-tests/

test_win7_x64:
  tags:
    - windows
    - selfhosted
    - win7
    - amd64
  needs:
    - job: build_windows
      artifacts: true
  script:
    - tests/run.ps1 artifacts-tests/

#test_linux:
#  image: debian:latest
#  tags:
#    - linux
#  needs:
#    - job: build_linux
#      artifacts: true
#  before_script:
#    - apt update && apt install -y libseccomp2
#  script:
#    - tests/run.sh artifacts-tests/
