[workspace]
resolver = "2"
members = [
    "policy",
    "ipc",
    "worker",
    "broker",
    "tests",
    "linux-entrypoint",
    "bindings/C/broker",
    "bindings/C/worker",
]

[profile.release]
lto = true
