name: Audit dependencies
on:
  push:
  pull_request:
  schedule:
    - cron: '30 7,17 * * *'

env:
  CARGO_TERM_COLOR: always
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

